/**
 * `nx make:queue <Name>` — scaffold a queue worker.
 *
 * Generates:
 *   - app/queue/workers/<name>.worker.ts  — @OnQueueReady handler class
 *   - app/queue/jobs/<name>.job.ts         — a `enqueue*` helper for callers
 *   - prints wiring instructions
 *
 * Usage:
 *   nx make:queue send-welcome-email --backend bullmq
 *   nx make:queue process-image --backend cloudflare
 *   nx make:queue notify --backend memory
 */

import { resolve } from "node:path";
import type { Command, CommandContext } from "../core/index.js";
import {
	flagBool,
	logger,
	nameVariants,
	render,
	writeFile,
} from "../core/index.js";

const WORKER_TEMPLATE = `
import { Inject, Injectable } from '@nexusts/core';
import { QueueService, OnQueueReady } from '@nexusts/queue';

/**
 * {{ name }} worker — generated by \`nx make:queue {{ name }}\`.
 *
 * Registers a handler for the \`{{ name }}\` job name on boot.
 */
@Injectable()
export class {{ name }}Worker {
  constructor(@Inject(QueueService.TOKEN) private readonly queue: QueueService) {}

  @OnQueueReady()
  async register(): Promise<void> {
    await this.queue.process('{{ name }}', async (data, ctx) => {
      ctx.prefix; // → "[queue:{{ name }}]"
      try {
        await this.handle(data as {{ name }}Data);
        return { status: 'completed' };
      } catch (err) {
        return {
          status: 'failed',
          error: err instanceof Error ? err : new Error(String(err)),
          willRetry: ctx.attempts < 3,
        };
      }
    });
  }

  /**
   * Replace this body with your actual worker logic.
   */
  async handle(data: {{ name }}Data): Promise<void> {
    // TODO: implement
  }
}

/**
 * Typed payload for the \`{{ name }}\` job.
 */
export interface {{ name }}Data {
  // TODO: define fields
  [key: string]: unknown;
}
`.trimStart();

const JOB_HELPER_TEMPLATE = `
import { Inject, Injectable } from '@nexusts/core';
import { QueueService } from '@nexusts/queue';
import type { {{ name }}Data } from './{{ kebab }}.worker.js';

/**
 * Helper for enqueuing \`{{ name }}\` jobs from controllers / services.
 * Generated by \`nx make:queue {{ name }}\`.
 */
@Injectable()
export class {{ name }}Job {
  constructor(@Inject(QueueService.TOKEN) private readonly queue: QueueService) {}

  /** Enqueue a single {{ name }} job. */
  async enqueue(data: {{ name }}Data, options?: {
    delaySeconds?: number;
    attempts?: number;
  }) {
    return this.queue.add('{{ name }}', data, options);
  }

  /** Enqueue many at once. */
  async enqueueBatch(items: {{ name }}Data[]) {
    return this.queue.addBatch(
      items.map((data) => ({ name: '{{ name }}', data })),
    );
  }
}
`.trimStart();

const WIRE_HINT = `
import { QueueService } from '@nexusts/queue';
import { %%NAME%%Job } from './queue/jobs/%%KEBAB%%.job.js';
import { %%NAME%%Worker } from './queue/workers/%%KEBAB%%.worker.js';

@Module({
  providers: [%%NAME%%Job, %%NAME%%Worker],
})
export class QueueBindingsModule {}
`.trim();

export const makeQueueCommand: Command = {
	name: "make:queue",
	aliases: ["mq", "make-queue"],
	summary: "Scaffold a queue worker",
	description:
		"Generates a worker class + enqueue helper under app/queue/. The backend is read from nx.config.ts (or --backend).",
	examples: [
		"nx make:queue send-welcome-email",
		"nx make:queue process-image --backend cloudflare",
		"nx make:queue notify --backend memory",
	],
	flags: [
		{
			name: "backend",
			description: "Override backend (bullmq|cloudflare|memory)",
		},
		{
			name: "no-job",
			description: "Skip the enqueue helper, only generate the worker",
		},
		{
			name: "no-worker",
			description: "Skip the worker class, only generate the enqueue helper",
		},
	],
	async run(ctx: CommandContext): Promise<number> {
		const name = ctx.positional[0];
		if (!name) {
			logger.error("Usage: nx make:queue <Name>");
			return 1;
		}

		const variants = nameVariants(name);
		const backend =
			(ctx.flags.backend as string | undefined) ??
			ctx.config.queue?.backend ??
			"memory";

		if (!["bullmq", "cloudflare", "memory"].includes(backend)) {
			logger.error(
				`Unknown backend: ${backend}. Allowed: bullmq, cloudflare, memory.`,
			);
			return 1;
		}

		logger.heading(`Scaffolding ${variants.pascal} (backend=${backend})`);

		// 1) Worker
		if (!flagBool(ctx.flags, "no-worker", false)) {
			const code = render(WORKER_TEMPLATE, {
				name: variants.pascal,
				kebab: variants.kebab,
			});
			const out = resolve(
				ctx.cwd,
				"app/queue/workers",
				`${variants.kebab}.worker.ts`,
			);
			if (writeFile(out, code, { skipIfExists: true })) {
				logger.success(`created ${out}`);
			} else {
				logger.warn(`skipped (exists): ${out}`);
			}
		}

		// 2) Enqueue helper
		if (!flagBool(ctx.flags, "no-job", false)) {
			const code = render(JOB_HELPER_TEMPLATE, {
				name: variants.pascal,
				kebab: variants.kebab,
			});
			const out = resolve(
				ctx.cwd,
				"app/queue/jobs",
				`${variants.kebab}.job.ts`,
			);
			if (writeFile(out, code, { skipIfExists: true })) {
				logger.success(`created ${out}`);
			} else {
				logger.warn(`skipped (exists): ${out}`);
			}
		}

		logger.blank();
		logger.heading("Next steps");
		logger.info(`1. Add QueueModule.forRoot() to your AppModule.imports:`);
		logger.info(`     QueueModule.forRoot({ backend: '${backend}', ... })`);
		logger.info(`2. Wire the worker + helper as providers:`);
		logger.info(
			render(WIRE_HINT, { name: variants.pascal, kebab: variants.kebab })
				.split("\n")
				.map((l) => `     ${l}`)
				.join("\n"),
		);
		logger.info(
			`3. Replace the TODO in ${variants.pascal}Worker.handle() with your logic.`,
		);
		logger.blank();

		return 0;
	},
};

export default makeQueueCommand;
