/**
 * `nx make:session <Name>` — scaffold a session helper class.
 *
 * Generates:
 *   - app/session/services/<name>.session.ts
 *     — an @Injectable class with example session helpers
 *
 * Usage:
 *   nx make:session Cart
 *   nx make:session Flash --data "message: string"
 */

import { resolve } from "node:path";
import type { Command, CommandContext } from "../core/index.js";
import { logger, nameVariants, render, writeFile } from "../core/index.js";

const SESSION_TEMPLATE = `
import { Inject, Injectable } from '@nexusts/core';
import { SessionService } from '@nexusts/session';
import type { SessionRecord } from '@nexusts/session';

/**
 * {{ name }} session helper — generated by \`nx make:session {{ name }}\`.
 *
 * Wraps SessionService with typed accessors for the {{ name }} session's
 * data. Use from controllers / services.
 */
@Injectable()
export class {{ name }}Session {
  constructor(@Inject(SessionService.TOKEN) private readonly sessions: SessionService) {}

  /** Read the current session record (or null). */
  async getCurrent(sessionId: string | null | undefined) {
    if (!sessionId) return null;
    return this.sessions.read(sessionId);
  }

  /** Patch the {{ name }} session's data. */
  async update(sessionId: string, patch: {{ name }}DataPatch) {
    return this.sessions.update(sessionId, { dataPatch: patch });
  }

  /** Destroy the session (logout-everywhere equivalent). */
  async destroy(sessionId: string) {
    return this.sessions.destroy(sessionId, 'logout');
  }
}

/**
 * Typed payload for the {{ name }} session.
 *
 * TODO: define the fields below to match your feature.
 */
export interface {{ name }}Data {
  // userId?: string;
  // createdAt?: string;
}

export type {{ name }}DataPatch = Partial<{{ name }}Data>;
`.trimStart();

export const makeSessionCommand: Command = {
	name: "make:session",
	aliases: ["msess", "make-session"],
	summary: "Scaffold a session helper class",
	description:
		"Generates an @Injectable session helper under app/session/services/.",
	examples: ["nx make:session Cart", "nx make:session Flash"],
	async run(ctx: CommandContext): Promise<number> {
		const name = ctx.positional[0];
		if (!name) {
			logger.error("Usage: nx make:session <Name>");
			return 1;
		}

		const variants = nameVariants(name);
		const code = render(SESSION_TEMPLATE, {
			name: variants.pascal,
			kebab: variants.kebab,
		});
		const out = resolve(
			ctx.cwd,
			"app/session/services",
			`${variants.kebab}.session.ts`,
		);

		if (writeFile(out, code, { skipIfExists: true })) {
			logger.success(`created ${out}`);
		} else {
			logger.warn(`skipped (exists): ${out}`);
		}

		logger.blank();
		logger.heading("Next steps");
		logger.info("1. Define the typed payload (replace the TODO interface).");
		logger.info(`2. Inject {{name}}Session in your controllers / services.`);
		logger.info("3. Bind it in the module's providers array.");
		logger.blank();

		return 0;
	},
};

export default makeSessionCommand;
