/**
 * Drizzle ORM model template — dialect-aware.
 *
 * Renders a Drizzle table schema + types. The right import path
 * (`drizzle-orm/pg-core`, `drizzle-orm/mysql-core`, `drizzle-orm/sqlite-core`,
 * `drizzle-orm/bun-sqlite`, `drizzle-orm/d1`) and column helpers are
 * selected by the caller.
 *
 * Context:
 *   name        — PascalCase class name (e.g. "User")
 *   kebab       — kebab-case file name (e.g. "user")
 *   tableName   — snake_case plural table name (e.g. "users")
 *   columns     — newline-separated column lines (rendered by command)
 *   importPath  — drizzle dialect module path
 *   idHelper    — 'serial' (pg), 'int' (mysql), 'integer' (sqlite/bun/d1)
 *   tsHelper    — 'integer' (pg), 'int' (mysql), 'integer' (sqlite/bun/d1)
 *   tsText      — 'text' for all dialects
 *   tsTimestamp — 'timestamp' (pg/mysql) or 'integer' (sqlite/d1)
 *   tsBool      — 'boolean' (pg/mysql) or 'integer' (sqlite/d1)
 *   tsDateMode  — '' (pg), '' (mysql), "{ mode: 'timestamp' }" (sqlite/d1)
 *   idType      — Drizzle column type for id (e.g. "serial", "integer")
 *   timestampType — Drizzle column type for createdAt/updatedAt
 */

export function renderDrizzleDialect(dialect: string): string {
	const spec = DIALECT_SPECS[dialect] ?? DIALECT_SPECS.sqlite;
	return `
import { ${spec.imports.join(", ")} } from '${spec.importPath}';

/**
 * {{ tableName }} — generated by \`nx make:model {{ name }}\`.
 */
export const {{ snake }} = ${spec.tableFn}('{{ tableName }}', {
  id: ${spec.idHelper}('id').primaryKey(${spec.idOpts}),
{{ columns }}
  createdAt: ${spec.tsTimestamp}('created_at'${spec.tsDateMode}).notNull()${spec.defaultTs},
  updatedAt: ${spec.tsTimestamp}('updated_at'${spec.tsDateMode})${spec.defaultTsUpdate},
});

export type {{ name }} = typeof {{ snake }}.$inferSelect;
export type New{{ name }} = typeof {{ snake }}.$inferInsert;
`.trimStart();
}

interface DialectSpec {
	imports: string[];
	importPath: string;
	tableFn: string;
	idHelper: string;
	idOpts: string;
	tsTimestamp: string;
	tsDateMode: string;
	defaultTs: string;
	defaultTsUpdate: string;
}

const DIALECT_SPECS: Record<string, DialectSpec> = {
	postgres: {
		imports: [
			"pgTable",
			"serial",
			"text",
			"timestamp",
			"boolean",
			"integer",
			"bigint",
		],
		importPath: "drizzle-orm/pg-core",
		tableFn: "pgTable",
		idHelper: "serial",
		idOpts: "",
		tsTimestamp: "timestamp",
		tsDateMode: "",
		defaultTs: ".defaultNow()",
		defaultTsUpdate: "",
	},
	"bun-sqlite": {
		imports: ["sqliteTable", "integer", "text"],
		importPath: "drizzle-orm/sqlite-core",
		tableFn: "sqliteTable",
		idHelper: "integer",
		idOpts: "{ autoIncrement: true }",
		tsTimestamp: "integer",
		tsDateMode: ", { mode: 'timestamp' }",
		defaultTs: ".$defaultFn(() => Date.now())",
		defaultTsUpdate: ".$defaultFn(() => Date.now())",
	},
	sqlite: {
		imports: ["sqliteTable", "integer", "text", "real"],
		importPath: "drizzle-orm/sqlite-core",
		tableFn: "sqliteTable",
		idHelper: "integer",
		idOpts: "{ autoIncrement: true }",
		tsTimestamp: "integer",
		tsDateMode: ", { mode: 'timestamp' }",
		defaultTs: ".$defaultFn(() => Date.now())",
		defaultTsUpdate: ".$defaultFn(() => Date.now())",
	},
	d1: {
		imports: ["sqliteTable", "integer", "text", "real"],
		importPath: "drizzle-orm/d1",
		tableFn: "sqliteTable",
		idHelper: "integer",
		idOpts: "{ autoIncrement: true }",
		tsTimestamp: "integer",
		tsDateMode: ", { mode: 'timestamp' }",
		defaultTs: ".$defaultFn(() => Date.now())",
		defaultTsUpdate: ".$defaultFn(() => Date.now())",
	},
	mysql: {
		imports: [
			"mysqlTable",
			"int",
			"text",
			"timestamp",
			"boolean",
			"bigint",
			"double",
		],
		importPath: "drizzle-orm/mysql-core",
		tableFn: "mysqlTable",
		idHelper: "int",
		idOpts: "{ autoIncrement: true }",
		tsTimestamp: "timestamp",
		tsDateMode: "",
		defaultTs: ".defaultNow()",
		defaultTsUpdate: "",
	},
};

/** Per-dialect TS-type for a column flag. */
export function mapDrizzleType(dialect: string, type: string): string {
	const t = type.toLowerCase();
	if (t === "text" || t === "string" || t === "varchar") return "text";
	if (t === "int" || t === "integer") {
		return dialect === "mysql" ? "int" : "integer";
	}
	if (t === "bigint" || t === "bigintunsigned")
		return dialect === "mysql" ? "bigint" : "bigint";
	if (t === "bool" || t === "boolean")
		return dialect === "mysql" ? "boolean" : "boolean";
	if (t === "float" || t === "number" || t === "real" || t === "double") {
		return dialect === "mysql" ? "double" : "real";
	}
	if (t === "datetime" || t === "timestamp" || t === "date") {
		return dialect === "mysql"
			? "timestamp"
			: dialect === "postgres"
				? "timestamp"
				: "integer";
	}
	if (t === "json" || t === "jsonb") {
		return dialect === "mysql" ? "text" : "text";
	}
	return "text";
}

/** Whether the column needs a notNull() modifier by default. */
export function shouldBeNotNull(type: string): boolean {
	return type !== "text";
}
